### PR TITLE
Account for PRs approved by QE

### PR DESCRIPTION
**Pull request by aravindhp**
Check if PRs have been approved by QE and don't include them in the capacity calculations.

### CODE REVIEW

**Comment by aravindhp** [comment]
If we decide to go with the [rules engine](https://github.com/openshift/patchmanager/pull/30),  a more elegant approach would be to add an `allow` rule for this.

**Comment by mfojtik** [comment]
@aravindhp I think rule engine would be more appropriate here, it was built to support cases like this. I just merged the PR :-)

**Comment by aravindhp** [comment]
Awesome, @mfojtik. I will rework the PR to use the rules engine.

**Pull request closed without merging**
